version: "{build}"

install:
  - ps: $nodejs_version = Get-Content .nvmrc -Raw | foreach{ $_.Trim()}
  - ps: Install-Product node $nodejs_version x64
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm run static
  - npm test

matrix:
  fast_finish: true
