language: node_js
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  apt:
    update: true
    packages:
      - libtool
      - libsecret-1-dev
      - automake
      - autoconf
      - nasm
      - libgtk2.0-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2
services:
  - xvfb
env:
  global:
    #saucelabs
    - secure: 0dEI1QivjPDVNfew5wtuu9z2JSUOV0y1yPKqDQFrEXofKpiPgcR4fwew4HpJRum6GVOQlzFnudV9zX/f/9+RYPh2X7hT+snv0bOFJH0H86xAIRxlmg7UbjCOEyzR5LjWiSJL0EEuFskZyhuVoCjjvJg6YwMcZySW5pYpzZZlGOZ/4MUtf0Ukm9nZFK+vo0bHl5NZ78/bAqtZw9qeO7BuesoD0wQ6LmKHtVl5jCG2saRMw20wdvkENCsn3lR9mUbsBjQkO8k/bqJERCwpQb8kWsRoQ20tq+n3vWZiHsDelYW3Vfk5qQ6lDu890v2NvQa5n0x2FeR20E3qVHdbY0lBreKt9n2MF8PFxv3cxqZ0sfX8S4hbmIdPIpWDd6BTyrElatizKgVqnDL0ZCbv3iJREbWB8Gcnijy9dPcBkqru4lavTKpiQQphugaWHpgeSHcAB4XEKOOplvbtoPl/jNikvAXExTwtC8AHCwkizXXFlaJN+MTjrvT7vF/SCP2IzIFDsRYAMa80fFKSx+FZnRbMK4SHUdM6uLsEmTtYKsXNY4dUm+b52Yvcb88psAqM/UcZOr+gSuRKXTh3X5t9rSQ7QJt+U12DRTD4pAS5C+rxu6/ycWxtCVzLRNkeGdapsmmK2MALzPYDTJNiUhrdichwxFh66zvawzO+hJYBGX4u0b8=
    #github
    - secure: Dx/QegBVkAnFd5q4ak0K7Cy2RTWIrFXBkIN5M5hu+nKF8WqrNYh0pAjFnWXix6Sn2WVgNQgv4Nwli6XLqXR/eUJh260wYrlfQSbZ+9ADA8U1FTgngueRxqpKlZq3/33q8OXPznEGgG7V5PYcdxBlbG7M0UJE16HwRcF8/iYRtXHUFhxD9n9IKoEt8pKBieQZwk+10epyB9pGCXXR/HD7hCEsM079lGOE0ReHJp0cxQNPRdFTcsEG7tfYGRXwp5W9eRDAVPnt2f89MW75L87qOXdu/gXlvUjdQcwo5KPhSH9ipGDyuZoQ2QS+i67j4MjzGiwZH+DbwisQesMqarNvg+FEc6WXm3tt75GFHH9h2tU4GI6fXr9/8PuhNcJDt4PmuuVeLPlOMCep+FXeRn38FIaN3+UKMEBrBfS1GA8Jb4Gq20QORf0N2HczhIjVf/13U9mqAAz4e28Dolhh3ddL0f30uJumov2J7MCcdYio9g0JY+RgwrOXKTeS5KvT6EC40+daL+xdH2sXoXrI2Hv8RoDO7ciQLZYYAVLZ9HQRRdBoPW8A76S5T0yY7wPqgArbcsRR8f2GhFh5pbe2UPlFGazRpQqUjIKRl7LS+4p8FQJh/ojQZYg5BEd4g/leNM+tkfCZj+VbwOyazfg4K0GK3eEeraizbkVPGYAZy0V8Z4c=
    #cypress
    - secure: tDmi0q7FWgCvn1ER6SsiSm1fJXGU1TJHaah16/L/UQ1pJe0Pp1BNiZzK8QwHQPOLFFVIGny6URrHcpo/D5F4PTcRabtjfZvi3UiKpBF0kgEzKlUsoZNs5bZ4dw2tocwJjtkQ9WokYPC13RanzBQK0kx0J6cN32a1jtm6Ov4VCzOl0ujRanOFLkCwokEsnninlTfGYfAJ7vstgYPToc/KttCyoLLu8S2s6uQ8TYOQWil4EAf/e3uktnqkyMBXJM6orlN9iCmVo2NcpvIPiQIgQt+YF42nLTddyWkuMlDxaLO/TV75UtemaoYbRPJScdVkZVq02/bTl7ZPQ1TEQIN+bwHc9RykBTKTlVgK1yPLN92nk/AXM/Apzg+xSAJy0gh7pMuLocmK4u1qOO8PrC5piHjzSaJ1ljsmQqAarXb6FgBpzra6uWlvfSeIWu7TILm0RxE4GtaqJQ5nmnR8hCz8pGQAdofANqd/VEE6ADpNBzThD0FS1iDr6/dTOcR4VCoP8LiMqIKI7zA368w/WjTfBS9SbXcKw0Et2B2gqDMZ+9i2wD9mgTVn/Ayf9tiLKHLlFWeTOWeC1NgfL88rvNdW6i0TlvkK9Q0cxpMljGgqoIwwrR3dBGqnH+ufuAakULHlExWpktdMuFlYRixwKi5jdFZIRIeM3rotljPGP7axPdI=
    #snyk
    - secure: "FX6kiDWQELo076iQDwW5m5zdRQMqV+wYBOcx4B+UwA+PnpmVaSv5FksjF45ruefp26RXLfSaytj0iE70huGqb6e34SyqJndPmrU58kBq6vz00iw94hwZBUmfaibNd0Q7oeRGmmZWwE5oZt2ll8RMzI9K95w+rFeHy9hXlFG2zCFU51RgQsc8pCxYjphbt6ki2kwmvtdBkCuMOckNI5QG/lSU9uiuNjys3/sBLmtq67JZbYNP3RQolm5Y86mvESkvHrEf0afQNFqciJW8TW4sj5J9ZSJXcYh0GWWPr7sId7mqtwyY0ciTbdgwLX0Aa/1D9o2eIIPfL2U5hNrmwP8OULWXQ/9+8p4r5RZqswy6SxtjHfSFFW0CTDgiuYt7c4bj5v5UbekOcrQr6PlF1amI2kFe8V7Q9zzVMjyhIDEV3ndEC2XLQDOppCdnLetAcRuK4j/jGeJp8fyWcIMeJLlB0CZ8tVxgwuDD9R8903TJw0xxETI4cfM1AdZPEXPUod/6htz+N17kaVFmH3Z69mLdIMA4+MbTiVObmefep1s7sxFU/flkQXOV3G5ij/2CkyO3RVlXICXNgOThJ33Sbmftv482cAiW4VHMZPN15AvIiPuDxY0gE5vFcJkqhKXUFw7v+gLSkva0kyv8D6VfcV7cRnZKMvtGlMRr+A5247C/8K4="
cache:
  npm: true
  directories:
    - dist
    - reports
jobs:
  include:
    - stage: prepare cache
      # before_install:
      #   - ls dist
      #   # image optimization dependencies
      #   - sudo apt-get install libtool libsecret-1-dev automake autoconf nasm
      #   # cypress dependencies
      #   - sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      install:
        - npm i
    - stage: website
      script: npm run static --base=/gp-vue-boilerplate/
    - stage: storybook
      script: npm run storybook:prod
    - stage: test
      script:
        - npm install wait-on mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator --no-save
        - npm run start-static & npx wait-on http://localhost:8050
        - export CYPRESS_PROJECT_ID=575mhd
        - npm run cypress:run -- --record
        - kill $(jobs -p) || true
        - npx mochawesome-merge --reportDir ./reports/cypress/results > ./reports/cypress/mochawesome.json
        - npx mochawesome-report-generator ./reports/cypress/mochawesome.json --reportDir=./reports/ --reportFilename=cypress.html
    - stage: deploy
      on:
        branch: master
      script:
        - npm install semantic-release @semantic-release/git @semantic-release/changelog --no-save
        - npm run semantic-release
        - mkdir dist/reports/
        - mv reports/* dist/reports/
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
        local_dir: dist/
        on:
          branch: master
# script:
#   - npm run start & npx wait-on http://localhost:8050
#   - export CYPRESS_PROJECT_ID=575mhd
#   - npm run cypress:run -- --record
#   - kill $(jobs -p) || true

