language: node_js
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  apt:
    update: true
    packages:
      - libjpeg-dev
      - libpng-dev
      - libgif-dev
      - libgtk2.0-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2
services:
  - xvfb
env:
  global:
    #packtracker
    - secure: "K7azcCqLptmg4uQUzLHyoDmqo9hmcjX+WK9VkhzMhvDRCiMCxkK0kOm6GXWOfCroeTN97EIkDx/5MrLUIXGUwEiAueNCeIkNEgY5hKTJRuWib6hBdc1ArghJiCAdVhIoDYJsRasrJ7B4QbcLFjoHAYvAPKArFNlVN5+ZJCQ+v1ZPT2yaItkuRBVy+9vLxPN75yJwciPC+ruj19WvMgmWOH/nlmYCYm2830b7IjZkFuUm67/aEdjnhXaOVErmXCT6sASk/gGlX6XqejChuIze5BC5j5phYiyNQRbY5D/CzhpPmGdbDYPo85/pusixGSLYN7cC8XoKOvWrdSXsHyBbkfmXPfG2rDrQ2p6Y+MVEyBEbbq+yZvCD6LLG25koq4N3rBu77ZDbLw977hjoWmVC1IdX+1uWTdRfcuNY112UV8vvrReLHdZzC2KHfiuNvzq4jV2ogNfQvFexTIAZk7mD8uoe3+uXgCg7nMMKOLHRx3TyqK6YPT0fwrffcMpdBnaIAyvd68gPOB4bD5PWr8/KLLQFq4sVcXQhiTp33p9iKZTr0proo7Vtp79HFn7u48nyKPzdZZKIUeKCsqi+TQNWKCifz34xyYw2zNpgC0BYlXRJ4BRcB7vC2+D1OJjQGmAenaoKz2L2gCjG0uheBs1FP41RCBcRElf2ce39zX1qtDY="
    #saucelabs
    - secure: 0dEI1QivjPDVNfew5wtuu9z2JSUOV0y1yPKqDQFrEXofKpiPgcR4fwew4HpJRum6GVOQlzFnudV9zX/f/9+RYPh2X7hT+snv0bOFJH0H86xAIRxlmg7UbjCOEyzR5LjWiSJL0EEuFskZyhuVoCjjvJg6YwMcZySW5pYpzZZlGOZ/4MUtf0Ukm9nZFK+vo0bHl5NZ78/bAqtZw9qeO7BuesoD0wQ6LmKHtVl5jCG2saRMw20wdvkENCsn3lR9mUbsBjQkO8k/bqJERCwpQb8kWsRoQ20tq+n3vWZiHsDelYW3Vfk5qQ6lDu890v2NvQa5n0x2FeR20E3qVHdbY0lBreKt9n2MF8PFxv3cxqZ0sfX8S4hbmIdPIpWDd6BTyrElatizKgVqnDL0ZCbv3iJREbWB8Gcnijy9dPcBkqru4lavTKpiQQphugaWHpgeSHcAB4XEKOOplvbtoPl/jNikvAXExTwtC8AHCwkizXXFlaJN+MTjrvT7vF/SCP2IzIFDsRYAMa80fFKSx+FZnRbMK4SHUdM6uLsEmTtYKsXNY4dUm+b52Yvcb88psAqM/UcZOr+gSuRKXTh3X5t9rSQ7QJt+U12DRTD4pAS5C+rxu6/ycWxtCVzLRNkeGdapsmmK2MALzPYDTJNiUhrdichwxFh66zvawzO+hJYBGX4u0b8=
    #github
    - secure: Dx/QegBVkAnFd5q4ak0K7Cy2RTWIrFXBkIN5M5hu+nKF8WqrNYh0pAjFnWXix6Sn2WVgNQgv4Nwli6XLqXR/eUJh260wYrlfQSbZ+9ADA8U1FTgngueRxqpKlZq3/33q8OXPznEGgG7V5PYcdxBlbG7M0UJE16HwRcF8/iYRtXHUFhxD9n9IKoEt8pKBieQZwk+10epyB9pGCXXR/HD7hCEsM079lGOE0ReHJp0cxQNPRdFTcsEG7tfYGRXwp5W9eRDAVPnt2f89MW75L87qOXdu/gXlvUjdQcwo5KPhSH9ipGDyuZoQ2QS+i67j4MjzGiwZH+DbwisQesMqarNvg+FEc6WXm3tt75GFHH9h2tU4GI6fXr9/8PuhNcJDt4PmuuVeLPlOMCep+FXeRn38FIaN3+UKMEBrBfS1GA8Jb4Gq20QORf0N2HczhIjVf/13U9mqAAz4e28Dolhh3ddL0f30uJumov2J7MCcdYio9g0JY+RgwrOXKTeS5KvT6EC40+daL+xdH2sXoXrI2Hv8RoDO7ciQLZYYAVLZ9HQRRdBoPW8A76S5T0yY7wPqgArbcsRR8f2GhFh5pbe2UPlFGazRpQqUjIKRl7LS+4p8FQJh/ojQZYg5BEd4g/leNM+tkfCZj+VbwOyazfg4K0GK3eEeraizbkVPGYAZy0V8Z4c=
    #cypress
    - CYPRESS_PROJECT_ID=575mhd
    - secure: tDmi0q7FWgCvn1ER6SsiSm1fJXGU1TJHaah16/L/UQ1pJe0Pp1BNiZzK8QwHQPOLFFVIGny6URrHcpo/D5F4PTcRabtjfZvi3UiKpBF0kgEzKlUsoZNs5bZ4dw2tocwJjtkQ9WokYPC13RanzBQK0kx0J6cN32a1jtm6Ov4VCzOl0ujRanOFLkCwokEsnninlTfGYfAJ7vstgYPToc/KttCyoLLu8S2s6uQ8TYOQWil4EAf/e3uktnqkyMBXJM6orlN9iCmVo2NcpvIPiQIgQt+YF42nLTddyWkuMlDxaLO/TV75UtemaoYbRPJScdVkZVq02/bTl7ZPQ1TEQIN+bwHc9RykBTKTlVgK1yPLN92nk/AXM/Apzg+xSAJy0gh7pMuLocmK4u1qOO8PrC5piHjzSaJ1ljsmQqAarXb6FgBpzra6uWlvfSeIWu7TILm0RxE4GtaqJQ5nmnR8hCz8pGQAdofANqd/VEE6ADpNBzThD0FS1iDr6/dTOcR4VCoP8LiMqIKI7zA368w/WjTfBS9SbXcKw0Et2B2gqDMZ+9i2wD9mgTVn/Ayf9tiLKHLlFWeTOWeC1NgfL88rvNdW6i0TlvkK9Q0cxpMljGgqoIwwrR3dBGqnH+ufuAakULHlExWpktdMuFlYRixwKi5jdFZIRIeM3rotljPGP7axPdI=
    #snyk
    - secure: "FX6kiDWQELo076iQDwW5m5zdRQMqV+wYBOcx4B+UwA+PnpmVaSv5FksjF45ruefp26RXLfSaytj0iE70huGqb6e34SyqJndPmrU58kBq6vz00iw94hwZBUmfaibNd0Q7oeRGmmZWwE5oZt2ll8RMzI9K95w+rFeHy9hXlFG2zCFU51RgQsc8pCxYjphbt6ki2kwmvtdBkCuMOckNI5QG/lSU9uiuNjys3/sBLmtq67JZbYNP3RQolm5Y86mvESkvHrEf0afQNFqciJW8TW4sj5J9ZSJXcYh0GWWPr7sId7mqtwyY0ciTbdgwLX0Aa/1D9o2eIIPfL2U5hNrmwP8OULWXQ/9+8p4r5RZqswy6SxtjHfSFFW0CTDgiuYt7c4bj5v5UbekOcrQr6PlF1amI2kFe8V7Q9zzVMjyhIDEV3ndEC2XLQDOppCdnLetAcRuK4j/jGeJp8fyWcIMeJLlB0CZ8tVxgwuDD9R8903TJw0xxETI4cfM1AdZPEXPUod/6htz+N17kaVFmH3Z69mLdIMA4+MbTiVObmefep1s7sxFU/flkQXOV3G5ij/2CkyO3RVlXICXNgOThJ33Sbmftv482cAiW4VHMZPN15AvIiPuDxY0gE5vFcJkqhKXUFw7v+gLSkva0kyv8D6VfcV7cRnZKMvtGlMRr+A5247C/8K4="
cache:
  npm: true
  directories:
    - dist
    - reports
    - storybook
jobs:
  include:
    - stage: prepare cache
      name: install
      before_install:
        - rm -rf dist reports storybook
      install:
        - npm i
    - stage: website
      name: build
      script:
        # - echo $TRAVIS_PULL_REQUEST_BRANCH
        # - echo $TRAVIS_BRANCH
        # - echo $TRAVIS_COMMIT
        # - echo $TRAVIS_PULL_REQUEST_SHA
        - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then export PT_BRANCH=$TRAVIS_BRANCH; else export PT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; fi
        - if [ -z "$TRAVIS_PULL_REQUEST_SHA" ]; then export PT_COMMIT=$TRAVIS_COMMIT; else export PT_COMMIT=$TRAVIS_PULL_REQUEST_SHA; fi
        # - echo $PT_COMMIT
        # - echo $PT_BRANCH
        - npm run static --base=/gp-vue-boilerplate/
        - npm run packtracker
    - stage: storybook
      name: build
      script:
        - npm run storybook:prod
    - stage: test
      name: cypress
      install:
        - npm i mocha@5.2.0 mochawesome --no-save
      script:
        - npm run start:static & npx wait-on http://localhost:8050
        - npm run cypress:run -- --record
        - kill $(jobs -p) || true
        - npx mochawesome-merge ./reports/cypress/results/mochawesome*.json > ./reports/cypress/mochawesome.json
        - npx mochawesome-report-generator ./reports/cypress/mochawesome.json --reportDir=./reports/ --reportFilename=cypress.html
    - stage: deploy
      if: branch = master
      install:
        - npm i semantic-release @semantic-release/exec @semantic-release/git @semantic-release/changelog --no-save
      script:
        - npx semantic-release --provider=github
        - mkdir gh-pages gh-pages/storybook gh-pages/reports
        - cp -R dist/* gh-pages/
        - cp -R storybook/* gh-pages/storybook/
        - cp -R reports/* gh-pages/reports/
        - touch gh-pages/.nojekyll
      deploy:
        provider: pages
        cleanup: false
        keep_history: false
        github_token: $GH_TOKEN
        local_dir: gh-pages/
        on:
          branch: master
        edge: true

